const defaultProductDetail = {
  product_id: '',
  item_group_id: '',
  age_group: 'adult',
  gender: 'unisex',
  pattern: '',
  size: '',
  size_type: 'regular',
  size_system: 'US',
  gtin: '',
  brand: '',
  offer_id: '',
  product_main_id: 0,
  language: 'zh-CN',
  monetary_unit: 'USD',
  title: '',
  title_main: '',
  description: '',
  link: '',
  mobile_link: '',
  image_link: '',
  additional_image_link: [],
  lifestyle_image_link: [],
  google_product_category: '',
  google_product_category_id: '',
  product_type: { key: '', title: '' },
  product_type_id: '',
  color: '',
  material: '',
  price: '',
  sale_price: '',
  product_detail: [], // 商品属性
  product_highlight: '',
  productHeight: '',
  productLength: '',
  productWidth: '',
  productWeight: '',
  availability: 'in_stock',
  sizeUnit: 'cm',
  weightUnit: 'g',
  channel: 'online',
  feedLabel: null,
  adult: 'no',
  kind: 'content#product',
  identifierExists: false,
  contentLanguage: 'zh',
  targetCountry: 'CN',
  projectId: '',
};
const defaultCurrentProductMain = {
  id: '',
  title: '',
  offer_id: '',
  google_product_category: {
    key: 4,
    title: '动物/宠物用品>宠物用品>猫用品',
  },
  google_product_category_id: 4,
  gtin: '',
  brand: 'Limeet',
};
export { defaultCurrentProductMain, defaultProductDetail };
