const defaultProductDetail = {
  product_id: '',
  item_group_id: '',
  age_group: 'adult',
  gender: 'unisex',
  pattern: '',
  size: '',
  size_type: 'regular',
  size_system: 'US',
  gtin: '',
  brand: '',
  offer_id: '',
  product_main_id: 0,
  language: 'zh-CN',
  monetary_unit: 'USD',
  title: '',
  title_main: '',
  description: '',
  link: '',
  mobile_link: '',
  image_link: '',
  additional_image_link: [],
  lifestyle_image_link: [],
  google_product_category: '',
  google_product_category_id: '',
  product_type: '',
  product_type_id: '',
  product_type: { key: '', title: '' },
  product_type_id: '',
  color: '',
  material: '',
  price: '',
  sale_price: '',
  discount: '',
  product_detail: [], // 商品属性
  product_highlight: '',
  productHeight: '',
  productLength: '',
  productWidth: '',
  productWeight: '',
  availability: 'in_stock',
  sizeUnit: 'cm',
  weightUnit: 'g',
  channel: 'online',
  feedLabel: null,
  adult: false,
  kind: 'content#product',
  identifierExists: false,
  contentLanguage: 'zh',
  targetCountry: 'CN',
  projectId: '',
};
const defaultCurrentProductMain = {
  id: '',
  title_main: '',
  offer_id: '',
  google_product_category: {
    key: '4',
    title: '动物/宠物用品>宠物用品>猫用品',
  },
  google_product_category_id: '4',
  gtin: '',
  brand: 'Limeet',
  identifierExists: false, // 如果商品没有适合其类别的唯一商品标识符（如 GTIN、MPN 和品牌），则为 false。
  costPrice: 0,
  costFirstLegFreightRatio: 10,
  costFbaRatio: 50,
  costsAdvertisingRatio: 5,
  targetProfitRatio: 30,
  preSalePrice: 0,
  summaryKeywords: '',
};

const defaultCostsExchange = {
  costFirstLegFreightRatio: 10,
  costFbaRatio: 50,
  costsAdvertisingRatio: 5,
  targetProfitRatio: 30,
  USD: 0.14,
  JPY: 20.5,
  KRW: 188,
  CNY: 1,
};

const costsExchangeTypeCurrency = {
  US: 'USD',
  JP: 'JPY',
  KR: 'KRW',
  CN: 'CNY',
};

const defaultProductCustomType = {
  title_zh: '',
  title_en: '',
  title_ja: '',
  title_ko: '',
};

export {
  costsExchangeTypeCurrency,
  defaultCostsExchange,
  defaultCurrentProductMain,
  defaultProductCustomType,
  defaultProductDetail,
};
