export default {
  title: {
    title: '商品名',
    des: '商品的名称',
    rule: '最多包含 150 个字符。准确描述商品，并与着陆页上的商品名保持一致。请勿使用促销性文字（如“免运费”）、全部大写的词句，或噱头式的外语字符。针对拥有不同款式/规格的商品，添加颜色或尺寸等区别性特征。',
    exam: '男式珠地网眼 Polo 衫',
    required: true,
    link: '',
  },
  description: {
    title: '说明',
    des: '商品的说明',
    rule: '最多包含 5,000 个字符。准确描述商品，并与着陆页上的说明保持一致。请勿使用促销性文字（如“免运费”）、全部大写的字母，或噱头式的外语字符。只包含与相应商品有关的信息。请勿包含指向您商店的链接、促销信息、竞品详细信息、其他商品或配饰。设计好格式（例如使用换行符、列表或斜体），让您的说明条理清晰。',
    exam: '这款经典红色男士 Polo 衫由 100％ 有机棉制成，为修身款式，左胸位置绣有品牌徽标。冷水机洗；进口商品。',
    required: true,
    link: '',
  },
  link: {
    title: '链接',
    des: '商品的着陆页',
    rule: '使用经过验证的域名。以 http 或 https 开头。使用经过编码且符合 RFC 2396 或 RFC 1738 规范的网址。除非法律有要求，否则请勿链接到插页。',
    exam: 'http://www.example.com/asp/sp.asp?cat=12&id=1030',
    required: true,
    link: '',
  },
  image_link: {
    title: '商品主图',
    des: '商品的主图片网址',
    rule: '链接到商品的白底主图片。以 http 或 https 开头。使用经过编码且符合 RFC 2396 或 RFC 1738 规范的网址。确保 Google 可以抓取网址（使用允许 Googlebot 和 Googlebot-image 抓取网址的 robots.txt 配置）。',
    exam: 'http:// www.example.com/image1.jpg',
    required: true,
    link: '',
  },
  additional_image_link: {
    title: '附加图附件图片',
    des: '商品附加图的网址',
    rule: '图片可展示商品陈列环境或商品使用场景。可以包含图片或插图。通过多次添加此属性，最多可以提交 10 张商品附加图。',
    exam: 'http://www.example.com/image1.jpg',
    link: '',
  },
  mobile_link: {
    title: '移动版链接',
    des: '针对移动设备进行了优化的商品着陆页，当您为来自移动设备的流量和来自桌面设备的流量分配不同的网址时会用到',
    rule: '满足有关链接 [link] 属性的要求。',
    exam: 'http://www.m.example.com/asp/ sp.asp?cat=12 id=1030',
    link: '',
  },
  availability: {
    title: '库存状况',
    des: '商品的库存状况',
    rule: '提交准确的商品库存状况，并与着陆页和结账页上的库存状况保持一致。',
    exam: 'in_stock',
    required: true,
    link: '',
  },
  price: {
    title: '价格',
    des: '商品的价格',
    rule: '提交准确的商品价格和货币，并与着陆页和结账页上的价格保持一致。确保在着陆页和结账页上的醒目位置添加价格（采用目标国家/地区的货币）。确保商品能以提交的价格在线购买。确保目标国家/地区的所有客户都能以您提交的价格购买商品，而无需支付会员费用。请勿提交值为 0 的价格（合约移动设备的价格可以为 0）。',
    exam: '',
    required: true,
    link: '',
  },
  sale_price: {
    title: '促销价:',
    des: '商品的促销价',
    rule: '提交准确的商品价格和货币，并与着陆页和结账页上的价格保持一致。确保在着陆页和结账页上的醒目位置添加价格（采用目标国家/地区的货币）。确保商品能以提交的价格在线购买。确保目标国家/地区的所有客户都能以您提交的价格购买商品，而无需支付会员费用。请勿提交值为 0 的价格（合约移动设备的价格可以为 0）。在提交此属性（促销价）的同时，还需要将价格 [price] 属性设置为原价。',
    exam: '15.00 USD',
    link: '',
  },
  google_product_category: {
    title: 'Google 商品类别',
    des: 'Google 为商品定义的商品类别',
    rule: '只添加一种类别。添加最相关的类别。添加类别的完整路径或数字形式的类别 ID（但不要同时添加两者）。建议使用类别 ID。',
    exam: '服饰与配饰 > 服装 > 外衣 > 外套与夹克',
    required: true,
    link: '',
  },
  product_type: {
    title: '商品类型',
    des: '您为自己的商品定义的商品类别',
    rule: '添加完整的类别。例如，添加家居服 > 女 > 连衣裙 > 及地长裙，而不是仅添加“连衣裙”。只有第一个商品类型值会在 Google Ads 购物广告系列中用于整理出价和报告',
    exam: '家居服 > 女 > 连衣裙 > 及地长裙',
    link: '',
  },
  brand: {
    title: '品牌',
    des: '商品的品牌名称',
    rule: '提供消费者熟悉的商品品牌名称。为商品提供正确的品牌可确保实现最佳用户体验，从而带来最佳效果。',
    exam: '',
    required: true,
    link: '',
  },
  offer_id: {
    title: '商品货号',
    des: '实际生产商品的货号，同类一个商品货号，但有多个组合',
    rule: '',
    exam: 'LT0090、LT0090-01',
    required: true,
    link: '',
  },
  gtin: {
    title: 'GTIN',
    des: '商品的全球贸易项目代码 (GTIN)。支持UPC、EAN、JAN、ISBN、ITF-14',
    rule: '排除连字符与空格。为商品提供正确的 GTIN 可确保实现最佳用户体验，从而带来最佳效果。提供 GTIN 时，请务必确保其正确无误。如有疑问，则请勿提供此属性，例如切勿猜测或编造 GTIN 值。如果您在提交商品时提供的 GTIN 值不正确，那么您的商品会遭到拒批。提交配套商品实际制造商的 GTIN 和品牌。请勿提供原始设备制造商 (OEM) 品牌来指明您的商品与 OEM 品牌商品配套，或是 OEM 品牌商品的复制品。',
    exam: '',
    required: true,
    link: '',
  },
  age_group: {
    title: '年龄段',
    des: '商品所定位的受众特征',
    rule: '为每个商品添加一个值。对于有不同款式/规格的商品：为商品组 ID [item_group_id] 添加相同的值，并为年龄段添加不同的值。',
    exam: '黑色',
    link: '',
  },
  color: {
    title: '颜色',
    des: '商品的颜色',
    rule: '请勿使用非字母数字字符，例如“#fff000”。',
    exam: '黑色',
    link: '',
  },
  gender: {
    title: '适用性别',
    des: '您的商品所定位的性别。支持的值：男性 [male]、女性 [female]、男女通用 [unisex]',
    rule: '对于某些服饰与配饰（ID：166）类别，例如鞋带（ID：1856），此属性为推荐的属性而非必需属性，因为这些类别不区分性别。',
    exam: 'Unisex',
    link: '',
  },
  material: {
    title: '材质',
    des: '商品的面料或材质',
    rule: '如需为同一商品指定多种材质（并非款式/规格），请添加一种主要材质，然后在其后添加最多 2 种次要材质，并以 / 分隔。例如，请使用“棉/涤纶/氨纶”，而不是“棉涤纶氨纶”。对于有不同款式/规格的商品：为商品组 ID [item_group_id] 属性添加相同的值，并为材质属性添加不同的值',
    exam: '',
    link: '',
  },
  pattern: {
    title: '图案',
    des: '商品上印刷的图案或图形',
    rule: '对于有不同款式/规格的商品：为商品组 ID [item_group_id] 属性添加相同的值，并为图案属性添加不同的值。',
    exam: '条纹、波卡圆点、佩斯利花纹',
    link: '',
  },
  size: {
    title: '尺寸',
    des: '商品的尺寸',
    rule: '对于有不同款式/规格的商品：为商品组 ID [item_group_id] 添加相同的值，并为尺寸 [size] 添加不同的值。如果尺寸中包含多种规格，请将其精简为一个值。例如，“16/34 高”表示领口 16 英寸，袖长 34 英寸，适合“高”身材',
    exam: 'XL',
    link: '',
  },
  size_type: {
    title: '尺码类型',
    des: '服饰商品的裁剪规格。支持的值：标准 [regular]、小号 [petite]、孕妇 [maternity]、大 [big]、高 [tall]、加大 [plus]',
    rule: '最多可提交 2 个值。如果您不提交该属性，则默认值为 regular。',
    exam: 'maternity',
    link: '',
  },
  size_system: {
    title: '尺码体系',
    des: '商品使用的尺码体系所属的国家/地区。支持的值：US、UK、EU、DE、FR、JP、CN、IT、BR、MEX、AU',
    rule: '如果您不提交此属性，则默认值为您的目标国家/地区。',
    exam: 'US',
    link: '',
  },
  item_group_id: {
    title: '商品组',
    des: '由具有多种版本（款式/规格）的商品构成的商品组的 ID',
    rule: '为每组款式/规格使用不重复的专用值。尽可能使用父级 SKU。更新商品数据时请勿修改该值。只能使用有效的 Unicode 字符。当一组商品因以下一个或多个属性而存在差异时，可以为这组商品使用商品组 ID：颜色 [color]、尺寸 [size]、图案 [pattern]、材质 [material]、年龄段 [age_group]、适用性别 [gender]。',
    exam: 'AB12345',
    link: '',
  },
  product_length: {
    title: '商品长度',
    des: '商品的长度',
    rule: '添加尽可能多的商品计量属性。对每个商品尺寸属性（包括商品长度、宽度和高度）使用相同的计量单位。否则，系统将无法显示这些信息。',
    exam: '20 in',
    link: '',
  },
  product_width: {
    title: '商品宽度',
    des: '商品的宽度',
    rule: '添加尽可能多的商品计量属性。对每个商品尺寸属性（包括商品长度、宽度和高度）使用相同的计量单位。否则，系统将无法显示这些信息。',
    exam: '20 in',
    link: '',
  },
  product_height: {
    title: '商品高度',
    des: '商品的高度',
    rule: '添加尽可能多的商品计量属性。对每个商品尺寸属性（包括商品长度、宽度和高度）使用相同的计量单位。否则，系统将无法显示这些信息。',
    exam: '20 in',
    link: '',
  },
  productLength: {
    title: '商品长度',
    des: '商品的长度',
    rule: '添加尽可能多的商品计量属性。对每个商品尺寸属性（包括商品长度、宽度和高度）使用相同的计量单位。否则，系统将无法显示这些信息。',
    exam: '20 in',
    link: '',
  },
  productWidth: {
    title: '商品宽度',
    des: '商品的宽度',
    rule: '添加尽可能多的商品计量属性。对每个商品尺寸属性（包括商品长度、宽度和高度）使用相同的计量单位。否则，系统将无法显示这些信息。',
    exam: '20 in',
    link: '',
  },
  productHeight: {
    title: '商品高度',
    des: '商品的高度',
    rule: '添加尽可能多的商品计量属性。对每个商品尺寸属性（包括商品长度、宽度和高度）使用相同的计量单位。否则，系统将无法显示这些信息。',
    exam: '20 in',
    link: '',
  },
  product_weight: {
    title: '商品重量',
    des: '商品的重量',
    rule: '对于此属性，请使用组装后的实际商品重量。如果您的商品分成多个部分（例如多部分组成一个套装），请在商品详情中使用所有部分的整体总重。',
    exam: '3.5 lb',
    link: '',
  },
  product_detail: {
    title: '商品详情',
    des: '商品的技术规范或其他详细信息',
    rule: '不要添加其他属性涵盖的信息、全大写字母、噱头式的外语字符或促销性文字，也不要罗列关键字或搜索字词。不要添加价格、促销价、促销日期、运费、送达日期等信息，也不要添加其他与时间相关的信息或贵公司的名称。仅在值已确定的情况下提供属性名称和值。例如，如果某种食品类商品不属于素食，则提供“Vegetarian=False”。',
    exam: '常规:商品类型:数字播放器',
    link: '',
  },
  product_highlight: {
    title: '商品亮点',
    des: '商品最重要的亮点，至少3-7条',
    rule: '使用 3 到 7 个商品亮点。仅介绍商品本身。不要罗列关键字或搜索字词。不要添加促销性文字、全大写字母或噱头式的外语字符。·禁用特殊字符 ?、®、€、…、+、≠、0、中、£、￥、©、±、~、â等。·禁用任何表情符号。·禁用短语 生态友好、环境友好、抗微生物、抗菌、竹制、含竹类、大豆制成、含大豆等。·禁用保证信息 “全额退款”“如果不满意，请将其退回”“无条件保证，无限制”等。',
    exam: '支持数千款应用，包括 Netflix、YouTube 和 HBO Max',
    link: '',
  },
  ads_redirect: {
    title: '广告重定向',
    des: '用来为您的商品页面指定更多参数的网址。系统会将客户引导到该网址，而不是您为链接 [商品链接] 或移动版链接 [移动版链接] 属性提交的网址值。',
    rule: '为此属性提交的注册网域应与为链接 [link] 属性（以及移动版链接 [mobile_link] 属性，如果存在的话）提交的相同。',
    exam: 'http://www.example.com/product.html',
    link: '',
  },
  custom_label: {
    title: '自定义标签',
    des: '向商品分配的标签，有助于在购物广告系列中整理出价和报告。',
    rule: '使用您可以在购物广告系列中识别的值。该值不会向看到您的广告和非付费商品详情的客户显示。通过多次添加该属性，最多可以为每个商品提交 5 个自定义标签',
    exam: '季节性、清仓甩卖、节假日、促销、价格范围',
    link: '',
  },
  promotion_id: {
    title: '促销 ID',
    des: '一种用来将商品与促销信息相匹配的标识符',
    rule: '使用不重复的专用 ID（区分大小写），请勿使用空格或符号（例如 %、!）。<br/>如需将特定的促销信息映射到指定商品，您需要在商品数据和促销数据中提交同一促销 ID。<br/>通过多次添加该属性，最多可为一款商品提交 10 个促销 ID',
    exam: 'ABC123',
    link: '',
  },
  lifestyle_image_link: {
    title: '商品详情图',
    des: '此属性用于为商品添加生活风格图片的网址,仅适用于浏览型展示平台',
    rule: '使用的网址应指向采用受支持文件格式的图片。应以 http 或 https 开头，且符合 RFC 3986 标准。其中若包含符号或空格，则需替换为网址编码实体。确保 Google 能够抓取您的网址。    ',
    exam: 'https://www.example.com/rule.html',
    link: '',
  },
  excluded_destination: {
    title: '禁止的目标平台',
    des: '通过此设置，您可以指定不在特定类型的广告系列中宣传某件商品',
    rule: '支持的值：Shopping_ads、Buy_on_Google_listings、Display_ads、Local_inventory_ads、Free_listings、Free_local_listings、YouTube_Shopping',
    exam: 'Shopping_ads',
    link: '',
  },
  included_destination: {
    title: '允许的目标平台',
    des: '通过此设置，您可以指定允许在特定类型的广告系列中宣传某件商品',
    rule: '支持的值：Shopping_ads、Buy_on_Google_listings、Display_ads、Local_inventory_ads、Free_listings、Free_local_listings、YouTube_Shopping',
    exam: 'Shopping_ads',
    link: '',
  },
  shopping_ads_excluded_country: {
    title: '禁止展示购物广告的国家/地区',
    des: '通过此设置，您可以指定不在哪些国家/地区通过购物广告宣传您的商品',
    rule: '',
    exam: 'DE',
    link: '',
  },
  pause: {
    title: '暂停',
    des: '利用此设置，您可以为所有广告（包括购物广告、展示广告和本地商品目录广告）暂停及快速重新启用商品。商品最多可以暂停 14 天。如果商品暂停的时间超过 14 天，就会遭到拒批。如需重新批准，请移除此属性。',
    rule: '',
    exam: 'ads',
    link: '',
  },
  ships_from_country: {
    title: '发货国家/地区',
    des: '通过此设置，您可以提供您的商品通常的发货国家/地区',
    rule: '应仅提供该商品通常的发货国家/地区。',
    exam: '',
    link: '',
  },
  weightUnit: {
    title: '重量单位',
    des: '根据区域选择重量单位',
    rule: '',
    exam: '',
    link: '',
  },
  sizeUnit: {
    title: '尺寸单位',
    des: '根据区域选择尺寸单位',
    rule: '',
    exam: '',
    link: '',
  },
  productSize: {
    title: '商品尺寸',
    des: '根据区域选择尺寸单位',
    rule: '',
    exam: '',
    link: '',
  },
};
