const tableData = [
  {
    key: 632,
    title: '五金/硬件',
    children: [
      {
        key: 1910,
        title: '储罐',
      },
      {
        key: 499982,
        title: '小型发动机',
      },
      {
        key: 500096,
        title: '五金泵',
        children: [
          {
            key: 500100,
            title: '井泵/系统',
            isLeaf: 0,
            level: 3,
            parent: 500096,
            children: [],
          },
          {
            key: 500101,
            title: '实用泵',
            isLeaf: 0,
            level: 3,
            parent: 500096,
            children: [],
          },
          {
            key: 500099,
            title: '家用电器泵',
            isLeaf: 0,
            level: 3,
            parent: 500096,
            children: [],
          },
          {
            key: 500098,
            title: '泳池、喷泉与池塘泵',
            isLeaf: 0,
            level: 3,
            parent: 500096,
            children: [],
          },
          {
            key: 500097,
            title: '洒水器、助力器与灌溉系统泵',
            isLeaf: 0,
            level: 3,
            parent: 500096,
            children: [],
          },
          {
            key: 500102,
            title: '集水坑/下水道/污水泵',
            isLeaf: 0,
            level: 3,
            parent: 500096,
            children: [],
          },
        ],
      },
      {
        key: 2878,
        title: '五金/硬件',
        children: [
          {
            key: 500054,
            title: '五金紧固件',
            isLeaf: 1,
            level: 3,
            parent: 2878,
            children: [
              {
                key: 2195,
                title: '垫圈',
                isLeaf: 0,
                level: 4,
                parent: 500054,
                children: [],
              },
              {
                key: 2230,
                title: '子母螺丝/对锁螺丝',
                isLeaf: 0,
                level: 4,
                parent: 500054,
                children: [],
              },
              {
                key: 1739,
                title: '螺帽与螺栓',
                isLeaf: 0,
                level: 4,
                parent: 500054,
                children: [],
              },
              {
                key: 500055,
                title: '螺纹杆',
                isLeaf: 0,
                level: 4,
                parent: 500054,
                children: [],
              },
              {
                key: 2251,
                title: '螺钉',
                isLeaf: 0,
                level: 4,
                parent: 500054,
                children: [],
              },
              {
                key: 2408,
                title: '钉子',
                isLeaf: 0,
                level: 4,
                parent: 500054,
                children: [],
              },
              {
                key: 7062,
                title: '铆钉',
                isLeaf: 0,
                level: 4,
                parent: 500054,
                children: [],
              },
              {
                key: 1508,
                title: '镙钉套',
                isLeaf: 0,
                level: 4,
                parent: 500054,
                children: [],
              },
            ],
          },
          {
            key: 500030,
            title: '保护罩/隔音毯/覆盖物',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 8112,
            title: '地钉',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 505320,
            title: '墙壁插孔/支架',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 7270,
            title: '定位销/杆',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 3974,
            title: '工具存储与收纳',
            isLeaf: 1,
            level: 3,
            parent: 2878,
            children: [
              {
                key: 3919,
                title: '工作台',
                isLeaf: 0,
                level: 4,
                parent: 3974,
                children: [],
              },
              {
                key: 6876,
                title: '工具包/工具袋',
                isLeaf: 0,
                level: 4,
                parent: 3974,
                children: [],
              },
              {
                key: 500103,
                title: '工具收纳装置衬垫/内衬',
                isLeaf: 0,
                level: 4,
                parent: 3974,
                children: [],
              },
              {
                key: 3280,
                title: '工具柜',
                isLeaf: 0,
                level: 4,
                parent: 3974,
                children: [],
              },
              {
                key: 3980,
                title: '工具箱',
                isLeaf: 0,
                level: 4,
                parent: 3974,
                children: [],
              },
              {
                key: 2485,
                title: '工具腰带/战术腰带',
                isLeaf: 0,
                level: 4,
                parent: 3974,
                children: [],
              },
              {
                key: 4031,
                title: '工具袋',
                isLeaf: 0,
                level: 4,
                parent: 3974,
                children: [],
              },
              {
                key: 4199,
                title: '橡胶软管存储盒',
                isLeaf: 0,
                level: 4,
                parent: 3974,
                children: [],
              },
            ],
          },
          {
            key: 499933,
            title: '弹簧',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 8470,
            title: '抽屉滑轨',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 4696,
            title: '橱柜金属器件',
            isLeaf: 1,
            level: 3,
            parent: 2878,
            children: [
              {
                key: 4699,
                title: '柜门',
                isLeaf: 0,
                level: 4,
                parent: 4696,
                children: [],
              },
              {
                key: 4698,
                title: '柜门吸',
                isLeaf: 0,
                level: 4,
                parent: 4696,
                children: [],
              },
              {
                key: 232167,
                title: '橱柜/家具锁眼盖',
                isLeaf: 0,
                level: 4,
                parent: 4696,
                children: [],
              },
              {
                key: 4697,
                title: '橱柜拉手',
                isLeaf: 0,
                level: 4,
                parent: 4696,
                children: [],
              },
              {
                key: 4700,
                title: '橱柜拉手/把手',
                isLeaf: 0,
                level: 4,
                parent: 4696,
                children: [],
              },
            ],
          },
          {
            key: 6769,
            title: '气动软管',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 6770,
            title: '润滑油软管',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 7086,
            title: '混凝土模具',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 6841,
            title: '燃气软管',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 8113,
            title: '立柱底板',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 1318,
            title: '线圈',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 1979,
            title: '罩单',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 499981,
            title: '脚轮',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 7092,
            title: '角码/固定支架',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 7557,
            title: '警示带',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 1816,
            title: '过滤器/筛子',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 503731,
            title: '金属铸造模具',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 503773,
            title: '钩子、锁扣与紧固件',
            isLeaf: 1,
            level: 3,
            parent: 2878,
            children: [
              {
                key: 503770,
                title: '吊钩、夹具与卸扣',
                isLeaf: 0,
                level: 4,
                parent: 503773,
                children: [],
              },
              {
                key: 503764,
                title: '接链环/链节',
                isLeaf: 0,
                level: 4,
                parent: 503773,
                children: [],
              },
              {
                key: 502992,
                title: '调节扣',
                isLeaf: 0,
                level: 4,
                parent: 503773,
                children: [],
              },
              {
                key: 502978,
                title: '金属芯扎带/捆绑带',
                isLeaf: 0,
                level: 4,
                parent: 503773,
                children: [],
              },
            ],
          },
          {
            key: 1771,
            title: '铰链/合页',
            isLeaf: 0,
            level: 3,
            parent: 2878,
            children: [],
          },
          {
            key: 502977,
            title: '链子、金属丝和绳子',
            isLeaf: 1,
            level: 3,
            parent: 2878,
            children: [
              {
                key: 6298,
                title: '减震绳/弹力绳',
                isLeaf: 0,
                level: 4,
                parent: 502977,
                children: [],
              },
              {
                key: 6904,
                title: '实用金属线',
                isLeaf: 0,
                level: 4,
                parent: 502977,
                children: [],
              },
              {
                key: 6297,
                title: '拉紧带',
                isLeaf: 0,
                level: 4,
                parent: 502977,
                children: [],
              },
              {
                key: 5119,
                title: '棉麻绳/合股线',
                isLeaf: 0,
                level: 4,
                parent: 502977,
                children: [],
              },
              {
                key: 4469,
                title: '珠链',
                isLeaf: 0,
                level: 4,
                parent: 502977,
                children: [],
              },
              {
                key: 3053,
                title: '绳索/五金线缆',
                isLeaf: 0,
                level: 4,
                parent: 502977,
                children: [],
              },
              {
                key: 1492,
                title: '链条',
                isLeaf: 0,
                level: 4,
                parent: 502977,
                children: [],
              },
            ],
          },
          {
            key: 4988,
            title: '防水布',
            isLeaf: 1,
            level: 3,
            parent: 2878,
            children: [],
          },
        ],
      },
      {
        key: 499873,
        title: '供暖、通风及空调',
        children: [
          {
            key: 1519,
            title: '暖通空调系统控件',
            isLeaf: 1,
            level: 3,
            parent: 499873,
            children: [
              {
                key: 1897,
                title: '恒温器',
                isLeaf: 0,
                level: 4,
                parent: 1519,
                children: [],
              },
              {
                key: 500043,
                title: '恒湿器',
                isLeaf: 0,
                level: 4,
                parent: 1519,
                children: [],
              },
              {
                key: 2238,
                title: '控制面板',
                isLeaf: 0,
                level: 4,
                parent: 1519,
                children: [],
              },
            ],
          },
          {
            key: 500090,
            title: '空气干燥器/过滤干燥器',
            isLeaf: 0,
            level: 3,
            parent: 499873,
            children: [],
          },
          {
            key: 499874,
            title: '通气管道',
            isLeaf: 0,
            level: 3,
            parent: 499873,
            children: [],
          },
          {
            key: 2766,
            title: '通风管与通气管',
            isLeaf: 0,
            level: 3,
            parent: 499873,
            children: [],
          },
        ],
      },
      {
        key: 1167,
        title: '工具',
        children: [
          {
            key: 1184,
            title: '丝锥与冲模',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 5927,
            title: '五金喷火枪',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1221,
            title: '冲击扳手/起子',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 505315,
            title: '冲压机/尖钻',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1180,
            title: '刀具',
            isLeaf: 1,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 2080,
                title: '切管器',
                isLeaf: 0,
                level: 4,
                parent: 1180,
                children: [],
              },
              {
                key: 7562,
                title: '夹钳工具',
                isLeaf: 0,
                level: 4,
                parent: 1180,
                children: [],
              },
              {
                key: 1454,
                title: '手持金属剪/毛坯下料机',
                isLeaf: 0,
                level: 4,
                parent: 1180,
                children: [],
              },
              {
                key: 1181,
                title: '断线钳',
                isLeaf: 0,
                level: 4,
                parent: 1180,
                children: [],
              },
              {
                key: 1182,
                title: '玻璃刀',
                isLeaf: 0,
                level: 4,
                parent: 1180,
                children: [],
              },
              {
                key: 2726,
                title: '瓷砖/石头切割机',
                isLeaf: 0,
                level: 4,
                parent: 1180,
                children: [],
              },
              {
                key: 2411,
                title: '美工刀',
                isLeaf: 0,
                level: 4,
                parent: 1180,
                children: [],
              },
              {
                key: 1824,
                title: '钢筋切断机',
                isLeaf: 0,
                level: 4,
                parent: 1180,
                children: [],
              },
            ],
          },
          {
            key: 1832,
            title: '划线工具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1187,
            title: '刨子',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1923,
            title: '刨床',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 7030,
            title: '劈木机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 4325,
            title: '压实机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 2015,
            title: '压缩机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1391,
            title: '去毛刺机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1196,
            title: '取物工具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 6938,
            title: '喷砂机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1215,
            title: '填缝工具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1195,
            title: '外六角螺丝刀/螺丝刀套筒',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 5587,
            title: '多功能角磨机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 126,
            title: '小机车/手推车',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 2456,
            title: '工业振动器',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 2198,
            title: '工具刀',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 4919,
            title: '工具套装',
            isLeaf: 1,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 6965,
                title: '五金工具套装',
                isLeaf: 0,
                level: 4,
                parent: 4919,
                children: [],
              },
              {
                key: 4716,
                title: '电动工具组合套装',
                isLeaf: 0,
                level: 4,
                parent: 4919,
                children: [],
              },
            ],
          },
          {
            key: 2835,
            title: '工装夹具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 499887,
            title: '手持电动搅拌机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1185,
            title: '手柄',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1235,
            title: '锯',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 3516,
                title: '切割锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 3706,
                title: '台锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 3582,
                title: '带锯床',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 3494,
                title: '往复锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 3224,
                title: '手持圆锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 3594,
                title: '手锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 3517,
                title: '斜切锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 4633,
                title: '曲线锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 499985,
                title: '板锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 7077,
                title: '石材锯/瓷砖锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
              {
                key: 3725,
                title: '镂花锯',
                isLeaf: 0,
                level: 4,
                parent: 1235,
                children: [],
              },
            ],
          },
          {
            key: 338,
            title: '手电筒/头灯',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 2454,
                title: '头灯',
                isLeaf: 0,
                level: 4,
                parent: 338,
                children: [],
              },
              {
                key: 543689,
                title: '手电筒',
                isLeaf: 0,
                level: 4,
                parent: 338,
                children: [],
              },
            ],
          },
          {
            key: 130,
            title: '梯子/脚手架',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 1809,
                title: '工作平台',
                isLeaf: 0,
                level: 4,
                parent: 130,
                children: [],
              },
              {
                key: 2416,
                title: '折叠梯车',
                isLeaf: 0,
                level: 4,
                parent: 130,
                children: [],
              },
              {
                key: 635,
                title: '梯凳',
                isLeaf: 0,
                level: 4,
                parent: 130,
                children: [],
              },
              {
                key: 6928,
                title: '梯子',
                isLeaf: 0,
                level: 4,
                parent: 130,
                children: [],
              },
              {
                key: 1866,
                title: '脚手架',
                isLeaf: 0,
                level: 4,
                parent: 130,
                children: [],
              },
            ],
          },
          {
            key: 1563,
            title: '柱塞',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 7271,
            title: '木榫',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 6868,
            title: '木工压刨机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1171,
            title: '斧子',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1206,
            title: '敲钉机/打钉机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1584,
            title: '攻丝机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1179,
            title: '撬杠',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 3501,
            title: '挖孔锹',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1667,
            title: '折弯机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 5592,
            title: '投光灯/矿业工作灯',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1632,
            title: '扳手',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1819,
            title: '扩孔钻',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 3745,
            title: '打磨工具锉刀',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 503774,
            title: '打火机/火柴',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 7416,
            title: '检查镜',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 4672,
            title: '水泥专用刷',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1202,
            title: '油灰刮刀',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1305,
            title: '测量工具与传感器',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 4074,
                title: 'pH 计',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4757,
                title: '分贝仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 2330,
                title: '切刀辅助器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 2192,
                title: '卡尺',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1533,
                title: '卡规',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 2481,
                title: '卷尺',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1850,
                title: '圆规',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4756,
                title: '地震仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1374,
                title: '天气预报机/气象仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 2021,
                title: '尺子',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4759,
                title: '振动测量仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 7394,
                title: '换能器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1785,
                title: '探测仪/探测器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1991,
                title: '气体检测器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 3602,
                title: '气压表',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4755,
                title: '水分测定仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1191,
                title: '水平仪',
                isLeaf: 1,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1640,
                title: '流量计/控制器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 5487,
                title: '测距仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1459,
                title: '测量轮',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4022,
                title: '测高仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4754,
                title: '湿度计',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 6799,
                title: '热成像相机',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 2093,
                title: '热电偶/热电堆',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 503737,
                title: '电力检测/验电工具',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 5371,
                title: '盖革计数器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1413,
                title: '直尺',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1205,
                title: '直角尺',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1698,
                title: '秤',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 5515,
                title: '空气质量检测仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4758,
                title: '紫外线计',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4506,
                title: '红外线测温仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 4340,
                title: '经纬仪',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1207,
                title: '螺柱传感器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1732,
                title: '量规',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1198,
                title: '量角器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 1539,
                title: '钢筋定位器',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
              {
                key: 500058,
                title: '风速计',
                isLeaf: 0,
                level: 4,
                parent: 1305,
                children: [],
              },
            ],
          },
          {
            key: 2077,
            title: '涂刷工具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 2465,
                title: '喷漆工具',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
              {
                key: 2486,
                title: '喷笔',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
              {
                key: 6556,
                title: '油漆/涂料修边器',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
              {
                key: 6557,
                title: '油漆托盘/涂料托盘/颜料盘',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
              {
                key: 499888,
                title: '油漆搅拌器',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
              {
                key: 1774,
                title: '滚漆筒',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
              {
                key: 505325,
                title: '滤漆筛',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
              {
                key: 1300,
                title: '漆刷',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
              {
                key: 1699,
                title: '绘画海绵',
                isLeaf: 0,
                level: 4,
                parent: 2077,
                children: [],
              },
            ],
          },
          {
            key: 5828,
            title: '滤油器排油装置',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1603,
            title: '灯泡更换器',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 2792,
            title: '烟囱刷',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1220,
            title: '热风枪',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1238,
            title: '焊枪/等离子切割机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1236,
            title: '焊铁',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1469,
            title: '电线/电缆工具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 6461,
            title: '电线穿线器',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1193,
            title: '砌体工具',
            isLeaf: 1,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 1555,
                title: '作图线/构造线/建构线',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
              {
                key: 2337,
                title: '抹泥刀/镘刀/推刀',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
              {
                key: 2305,
                title: '水泥搅拌机',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
              {
                key: 2181,
                title: '泥刀',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
              {
                key: 7484,
                title: '灌浆海绵',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
              {
                key: 1799,
                title: '瓦工磨边机',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
              {
                key: 4132,
                title: '电动抹平机',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
              {
                key: 1668,
                title: '砌砖工具',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
              {
                key: 1450,
                title: '砌砖接缝刨',
                isLeaf: 0,
                level: 4,
                parent: 1193,
                children: [],
              },
            ],
          },
          {
            key: 1219,
            title: '研磨机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 5873,
            title: '磁性扫地机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1225,
            title: '磨光机/磨光器',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1644,
            title: '磨具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 4419,
            title: '磨块',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1188,
            title: '磨砂机',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1862,
            title: '管刷',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 2053,
            title: '管道清洗器',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1203,
            title: '螺丝刀',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1194,
            title: '起钉工具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1663,
            title: '车床',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1439,
            title: '钥匙状小工具',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1958,
            title: '钳子',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 1217,
            title: '钻机',
            isLeaf: 1,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 1465,
                title: '凿孔机',
                isLeaf: 0,
                level: 4,
                parent: 1217,
                children: [],
              },
              {
                key: 2629,
                title: '手持电钻',
                isLeaf: 0,
                level: 4,
                parent: 1217,
                children: [],
              },
              {
                key: 1367,
                title: '螺旋钻',
                isLeaf: 0,
                level: 4,
                parent: 1217,
                children: [],
              },
              {
                key: 1216,
                title: '钻床',
                isLeaf: 0,
                level: 4,
                parent: 1217,
                children: [],
              },
              {
                key: 1994,
                title: '风钻',
                isLeaf: 0,
                level: 4,
                parent: 1217,
                children: [],
              },
            ],
          },
          {
            key: 1169,
            title: '铁砧',
            isLeaf: 0,
            level: 3,
            parent: 1167,
            children: [],
          },
          {
            key: 7064,
            title: '铆接工具',
            isLeaf: 1,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 7065,
                title: '铆钉枪',
                isLeaf: 0,
                level: 4,
                parent: 7064,
                children: [],
              },
              {
                key: 7066,
                title: '铆钉钳',
                isLeaf: 0,
                level: 4,
                parent: 7064,
                children: [],
              },
            ],
          },
          { key: 1841, title: '铣具', isLeaf: 0, level: 3, parent: 1167, children: [] },
          { key: 5077, title: '铣床', isLeaf: 0, level: 3, parent: 1167, children: [] },
          {
            key: 1186,
            title: '锤子',
            isLeaf: 1,
            level: 3,
            parent: 1167,
            children: [
              {
                key: 2208,
                title: '手工锤子',
                isLeaf: 0,
                level: 4,
                parent: 1186,
                children: [],
              },
              {
                key: 505364,
                title: '电动锤',
                isLeaf: 0,
                level: 4,
                parent: 1186,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: 3650,
        title: '工具配件',
        children: [
          {
            key: 8117,
            title: '切割机配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 8118,
                title: '冲剪模具',
                isLeaf: 0,
                level: 4,
                parent: 8117,
                children: [],
              },
            ],
          },
          {
            key: 3470,
            title: '刨床配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 3210,
                title: '插齿刀',
                isLeaf: 0,
                level: 4,
                parent: 3470,
                children: [],
              },
            ],
          },
          {
            key: 7472,
            title: '加磁器/消磁器',
            isLeaf: 0,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 6939,
            title: '喷砂机配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 6940,
                title: '喷砂箱',
                isLeaf: 0,
                level: 4,
                parent: 6939,
                children: [],
              },
            ],
          },
          {
            key: 2174,
            title: '工具刀片',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 505831,
                title: '切刀/刮刀刀片',
                isLeaf: 0,
                level: 4,
                parent: 2174,
                children: [],
              },
              {
                key: 2202,
                title: '锯片',
                isLeaf: 0,
                level: 4,
                parent: 2174,
                children: [],
              },
            ],
          },
          {
            key: 4658,
            title: '工具台',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 4659,
                title: '锯台',
                isLeaf: 0,
                level: 4,
                parent: 4658,
                children: [],
              },
            ],
          },
          {
            key: 7326,
            title: '斧子配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 7369,
                title: '斧头',
                isLeaf: 0,
                level: 4,
                parent: 7326,
                children: [],
              },
              {
                key: 7370,
                title: '斧柄',
                isLeaf: 0,
                level: 4,
                parent: 7326,
                children: [],
              },
              {
                key: 505812,
                title: '楔形工具',
                isLeaf: 0,
                level: 4,
                parent: 7326,
                children: [],
              },
            ],
          },
          {
            key: 7019,
            title: '油漆工具配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 6887,
                title: '喷枪配件',
                isLeaf: 0,
                level: 4,
                parent: 7019,
                children: [],
              },
              {
                key: 328062,
                title: '油漆刷清洁溶液',
                isLeaf: 0,
                level: 4,
                parent: 7019,
                children: [],
              },
              {
                key: 7020,
                title: '滚漆筒配件',
                isLeaf: 0,
                level: 4,
                parent: 7019,
                children: [],
              },
            ],
          },
          {
            key: 5526,
            title: '测量工具与传感器配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 7415,
                title: '万用表配件',
                isLeaf: 0,
                level: 4,
                parent: 5526,
                children: [],
              },
              {
                key: 5556,
                title: '气体探测器配件',
                isLeaf: 0,
                level: 4,
                parent: 5526,
                children: [],
              },
              {
                key: 5557,
                title: '电气测试工具配件',
                isLeaf: 0,
                level: 4,
                parent: 5526,
                children: [],
              },
              {
                key: 503007,
                title: '秤配件',
                isLeaf: 0,
                level: 4,
                parent: 5526,
                children: [],
              },
            ],
          },
          {
            key: 3281,
            title: '烙铁配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 3609,
                title: '烙铁头',
                isLeaf: 0,
                level: 4,
                parent: 3281,
                children: [],
              },
              {
                key: 3629,
                title: '烙铁架',
                isLeaf: 0,
                level: 4,
                parent: 3281,
                children: [],
              },
            ],
          },
          {
            key: 6292,
            title: '电动工具充电器',
            isLeaf: 0,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 6295,
            title: '电动工具电池',
            isLeaf: 0,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 4487,
            title: '砂磨配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 3240,
                title: '砂纸/磨砂海绵擦',
                isLeaf: 0,
                level: 4,
                parent: 4487,
                children: [],
              },
            ],
          },
          {
            key: 499859,
            title: '研磨机配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 499860,
                title: '磨轮/研磨点',
                isLeaf: 0,
                level: 4,
                parent: 499859,
                children: [],
              },
              {
                key: 6471,
                title: '起子配件',
                isLeaf: 0,
                level: 4,
                parent: 499859,
                children: [],
              },
            ],
          },
          {
            key: 3944,
            title: '钻孔机/螺丝刀配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 6806,
                title: '孔锯/开孔锯',
                isLeaf: 0,
                level: 4,
                parent: 3944,
                children: [],
              },
              {
                key: 1540,
                title: '钻头/螺丝刀头',
                isLeaf: 0,
                level: 4,
                parent: 3944,
                children: [],
              },
              {
                key: 7140,
                title: '钻头延长杆',
                isLeaf: 0,
                level: 4,
                parent: 3944,
                children: [],
              },
              {
                key: 6378,
                title: '钻头研磨机',
                isLeaf: 0,
                level: 4,
                parent: 3944,
                children: [],
              },
              {
                key: 8276,
                title: '钻夹头',
                isLeaf: 0,
                level: 4,
                parent: 3944,
                children: [],
              },
              {
                key: 8275,
                title: '钻架和导引架',
                isLeaf: 0,
                level: 4,
                parent: 3944,
                children: [],
              },
            ],
          },
          {
            key: 7056,
            title: '锤子配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 7087,
                title: '气锤配件',
                isLeaf: 0,
                level: 4,
                parent: 7056,
                children: [],
              },
              {
                key: 7057,
                title: '锤头',
                isLeaf: 0,
                level: 4,
                parent: 7056,
                children: [],
              },
              {
                key: 7055,
                title: '锤柄',
                isLeaf: 0,
                level: 4,
                parent: 7056,
                children: [],
              },
            ],
          },
          {
            key: 6549,
            title: '锯配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 6501,
                title: '台锯配件',
                isLeaf: 0,
                level: 4,
                parent: 6549,
                children: [],
              },
              {
                key: 7515,
                title: '带锯工具配件',
                isLeaf: 0,
                level: 4,
                parent: 6549,
                children: [],
              },
              {
                key: 7345,
                title: '手持圆锯配件',
                isLeaf: 0,
                level: 4,
                parent: 6549,
                children: [],
              },
              {
                key: 6503,
                title: '斜截锯配件',
                isLeaf: 0,
                level: 4,
                parent: 6549,
                children: [],
              },
              {
                key: 7346,
                title: '竖锯配件',
                isLeaf: 0,
                level: 4,
                parent: 6549,
                children: [],
              },
            ],
          },
          {
            key: 3744,
            title: '镂铣机配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 3673,
                title: '铣刀',
                isLeaf: 0,
                level: 4,
                parent: 3744,
                children: [],
              },
              {
                key: 3300,
                title: '铣床/雕刻机',
                isLeaf: 0,
                level: 4,
                parent: 3744,
                children: [],
              },
            ],
          },
          {
            key: 505323,
            title: '鹤嘴锄/镐配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [
              {
                key: 505324,
                title: '鹤嘴锄把/镐把',
                isLeaf: 0,
                level: 4,
                parent: 505323,
                children: [],
              },
            ],
          },
          {
            key: 6907,
            title: '夹具',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 505810,
            title: '工具堵漏楔',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 5571,
            title: '工具套筒',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 8258,
            title: '工具安全绳',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 2447,
            title: '手电筒配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 2380,
            title: '排钉',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 499886,
            title: '搅拌工具桨叶',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [],
          },
          {
            key: 499947,
            title: '焊接配件',
            isLeaf: 1,
            level: 3,
            parent: 3650,
            children: [],
          },
        ],
      },
      {
        key: 115,
        title: '建材',
        children: [
          {
            key: 7112,
            title: '制模',
            isLeaf: 0,
            level: 3,
            parent: 115,
            children: [],
          },
          {
            key: 2729,
            title: '台面板',
            isLeaf: 0,
            level: 3,
            parent: 115,
            children: [],
          },
          {
            key: 7439,
            title: '吸音板/海绵',
            isLeaf: 0,
            level: 3,
            parent: 115,
            children: [],
          },
          {
            key: 2826,
            title: '地板与地毯',
            isLeaf: 0,
            level: 3,
            parent: 115,
            children: [],
          },
          {
            key: 7136,
            title: '墙壁/天花板用瓷砖',
            isLeaf: 0,
            level: 3,
            parent: 115,
            children: [],
          },
          {
            key: 7053,
            title: '墙板',
            isLeaf: 0,
            level: 3,
            parent: 115,
            children: [],
          },
          {
            key: 503775,
            title: '壁板',
            isLeaf: 0,
            level: 3,
            parent: 115,
            children: [],
          },
          {
            key: 2030,
            title: '天窗',
            isLeaf: 0,
            level: 3,
            parent: 115,
            children: [],
          },
          {
            key: 123,
            title: '屋顶材料',
            isLeaf: 1,
            level: 3,
            parent: 115,
            children: [
              {
                key: 8270,
                title: '屋面木瓦和砖瓦',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 2008,
                title: '屋顶防水板',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 4544,
                title: '排水沟配件',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 121,
                title: '水落管/雨水管',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 503776,
                title: '干壁',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 499949,
                title: '扶手/栏杆系统',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 505300,
                title: '挡风雨条/防寒保暖用品',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 125,
                title: '木材和片料',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 7004,
                title: '楼梯',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 120,
                title: '玻璃',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 6943,
                title: '百叶窗',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
              {
                key: 124,
                title: '窗',
                isLeaf: 0,
                level: 4,
                parent: 123,
                children: [],
              },
            ],
          },
          {
            key: 499772,
            title: '窗户五金',
            isLeaf: 1,
            level: 3,
            parent: 115,
            children: [
              {
                key: 499773,
                title: '窗户曲柄',
                isLeaf: 0,
                level: 4,
                parent: 499772,
                children: [],
              },
              {
                key: 503728,
                title: '窗框',
                isLeaf: 0,
                level: 4,
                parent: 499772,
                children: [],
              },
              {
                key: 503777,
                title: '钢筋与钢网',
                isLeaf: 0,
                level: 4,
                parent: 499772,
                children: [],
              },
            ],
          },
          {
            key: 119,
            title: '门',
            isLeaf: 1,
            level: 3,
            parent: 115,
            children: [
              {
                key: 4634,
                title: '房门',
                isLeaf: 0,
                level: 4,
                parent: 119,
                children: [],
              },
              {
                key: 4468,
                title: '车库门',
                isLeaf: 0,
                level: 4,
                parent: 119,
                children: [],
              },
            ],
          },
          {
            key: 6343,
            title: '门用五金',
            isLeaf: 1,
            level: 3,
            parent: 115,
            children: [
              {
                key: 1356,
                title: '门把手/门拉手',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 2665,
                title: '门挡',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 499970,
                title: '门推板',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 503727,
                title: '门框',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 2795,
                title: '门环',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 2972,
                title: '门铃',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 99338,
                title: '门锁孔盖',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 6446,
                title: '闭门器',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 6458,
                title: '阴极锁/阳极锁',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
              {
                key: 122,
                title: '隔热材料',
                isLeaf: 0,
                level: 4,
                parent: 6343,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: 503739,
        title: '建筑耗材',
        children: [
          {
            key: 503742,
            title: '五金胶/粘合剂',
            isLeaf: 0,
            level: 3,
            parent: 503739,
            children: [],
          },
          {
            key: 2212,
            title: '五金胶带/工业胶带',
            isLeaf: 0,
            level: 3,
            parent: 503739,
            children: [],
          },
          {
            key: 2277,
            title: '化学品',
            isLeaf: 1,
            level: 3,
            parent: 503739,
            children: [
              {
                key: 7470,
                title: '化粪池/污水处理用品',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 7503,
                title: '平台/栅栏清洁剂',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 500088,
                title: '打火机油',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 1749,
                title: '排水管清洁剂',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 6795,
                title: '氨',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 7504,
                title: '混凝土/砖石清洁剂',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 1479,
                title: '烟囱清洁剂',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 505319,
                title: '电气冷冻喷雾',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 1735,
                title: '酸中和剂',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 6191,
                title: '除冰剂',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
              {
                key: 505802,
                title: '墙壁修补混合物与灰泥',
                isLeaf: 0,
                level: 4,
                parent: 2277,
                children: [],
              },
            ],
          },
          {
            key: 503740,
            title: '涂料耗材',
            isLeaf: 1,
            level: 3,
            parent: 503739,
            children: [
              {
                key: 2058,
                title: '底漆',
                isLeaf: 0,
                level: 4,
                parent: 503740,
                children: [],
              },
              {
                key: 1648,
                title: '染料',
                isLeaf: 0,
                level: 4,
                parent: 503740,
                children: [],
              },
              {
                key: 2474,
                title: '油漆粘合剂',
                isLeaf: 0,
                level: 4,
                parent: 503740,
                children: [],
              },
              {
                key: 1361,
                title: '涂料',
                isLeaf: 0,
                level: 4,
                parent: 503740,
                children: [],
              },
              {
                key: 503738,
                title: '清漆和罩面漆',
                isLeaf: 0,
                level: 4,
                parent: 503740,
                children: [],
              },
              {
                key: 1753,
                title: '润滑剂',
                isLeaf: 0,
                level: 4,
                parent: 503740,
                children: [],
              },
              {
                key: 503741,
                title: '溶剂/脱漆剂/稀释剂',
                isLeaf: 0,
                level: 4,
                parent: 503740,
                children: [],
              },
              {
                key: 1995,
                title: '焊料/熔剂',
                isLeaf: 0,
                level: 4,
                parent: 503740,
                children: [],
              },
            ],
          },
          {
            key: 503743,
            title: '砖石耗材',
            isLeaf: 1,
            level: 3,
            parent: 503739,
            children: [
              {
                key: 2282,
                title: '水泥/灰浆/混凝土混合物',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 499876,
                title: '灌浆',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 3031,
                title: '砖和水泥砖',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 499958,
                title: '安全/人群控制栅栏',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 1788,
                title: '栅栏/围栏门',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 502983,
                title: '栅栏/门配件',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 502973,
                title: '栅栏板',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 1352,
                title: '栅栏柱',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 1919,
                title: '栅栏立柱/滑轨',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 502984,
                title: '格架',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
              {
                key: 502986,
                title: '花园边界/分界',
                isLeaf: 0,
                level: 4,
                parent: 503743,
                children: [],
              },
            ],
          },
          {
            key: 505305,
            title: '管道底漆',
            isLeaf: 0,
            level: 3,
            parent: 503739,
            children: [],
          },
          {
            key: 503744,
            title: '防护涂料/密封剂',
            isLeaf: 0,
            level: 3,
            parent: 503739,
            children: [],
          },
        ],
      },
      {
        key: 128,
        title: '栅栏/围栏',
        children: [],
      },
      {
        key: 543575,
        title: '燃料',
        children: [
          {
            key: 543577,
            title: '丙烷',
            isLeaf: 0,
            level: 3,
            parent: 543575,
            children: [],
          },
          {
            key: 543703,
            title: '家用燃料油',
            isLeaf: 0,
            level: 3,
            parent: 543575,
            children: [],
          },
          {
            key: 543576,
            title: '煤油',
            isLeaf: 1,
            level: 3,
            parent: 543575,
            children: [
              {
                key: 543578,
                title: '染色煤油',
                isLeaf: 0,
                level: 4,
                parent: 543576,
                children: [],
              },
              {
                key: 543579,
                title: '纯煤油',
                isLeaf: 0,
                level: 4,
                parent: 543576,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: 502975,
        title: '燃料罐/箱',
        children: [],
      },
      {
        key: 127,
        title: '电动/电气用品',
        children: [
          {
            key: 5533,
            title: '交流-直流转换器',
            isLeaf: 0,
            level: 3,
            parent: 127,
            children: [],
          },
          {
            key: 1218,
            title: '发电机',
            isLeaf: 0,
            level: 3,
            parent: 127,
            children: [],
          },
          {
            key: 4709,
            title: '发电机配件',
            isLeaf: 0,
            level: 3,
            parent: 127,
            children: [],
          },
          {
            key: 6833,
            title: '墙装插座控制器/感应器',
            isLeaf: 0,
            level: 3,
            parent: 127,
            children: [],
          },
          {
            key: 2377,
            title: '壁装插座板/开关面板',
            isLeaf: 0,
            level: 3,
            parent: 127,
            children: [],
          },
          {
            key: 4714,
            title: '太阳能光伏板',
            isLeaf: 0,
            level: 3,
            parent: 127,
            children: [],
          },
          {
            key: 4715,
            title: '太阳能组件',
            isLeaf: 0,
            level: 3,
            parent: 127,
            children: [],
          },
          {
            key: 2413,
            title: '家居自动化套装',
            isLeaf: 0,
            level: 3,
            parent: 127,
            children: [],
          },
          {
            key: 499768,
            title: '导管/外壳',
            isLeaf: 1,
            level: 3,
            parent: 127,
            children: [
              {
                key: 3797,
                title: '热收缩管',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 499770,
                title: '电气导管',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 4789,
                title: '延长线/接线板',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 2274,
                title: '接线帽',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 503729,
                title: '接线端子和电线连接头',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 1869,
                title: '插座/墙插',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 6375,
                title: '插排/电源延长线配件',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 6807,
                title: '断路器柜',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 7275,
                title: '电动马达',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 505318,
                title: '电压互感器/稳压器',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
              {
                key: 5627,
                title: '电器插头保护盖',
                isLeaf: 0,
                level: 4,
                parent: 499768,
                children: [],
              },
            ],
          },
          {
            key: 6459,
            title: '电开关',
            isLeaf: 1,
            level: 3,
            parent: 127,
            children: [
              {
                key: 1935,
                title: '照明开关',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 499932,
                title: '特种电气开关与继电器',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 500049,
                title: '电枢、转子与定子',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 2006,
                title: '电气安装盒/支架',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 499966,
                title: '电源输入装置',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 2345,
                title: '电线/电缆',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 2028,
                title: '电话/网线插座',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 499893,
                title: '碳刷',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 5142,
                title: '逆变器',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
              {
                key: 7183,
                title: '镇流器/启辉器',
                isLeaf: 0,
                level: 4,
                parent: 6459,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: 133,
        title: '管道',
        children: [
          {
            key: 1723,
            title: '水井用品',
            isLeaf: 0,
            level: 3,
            parent: 133,
            children: [],
          },
          {
            key: 2243,
            title: '水平尺',
            isLeaf: 0,
            level: 3,
            parent: 133,
            children: [],
          },
          {
            key: 2570,
            title: '水暖软管',
            isLeaf: 0,
            level: 3,
            parent: 133,
            children: [],
          },
          {
            key: 2216,
            title: '水管管道',
            isLeaf: 0,
            level: 3,
            parent: 133,
            children: [],
          },
          {
            key: 504635,
            title: '水管装置和部件',
            isLeaf: 1,
            level: 3,
            parent: 133,
            children: [
              {
                key: 1458,
                title: '固定板',
                isLeaf: 0,
                level: 4,
                parent: 504635,
                children: [],
              },
              {
                key: 504636,
                title: '排水装置',
                isLeaf: 0,
                level: 4,
                parent: 504635,
                children: [],
              },
              {
                key: 504637,
                title: '排水配件',
                isLeaf: 1,
                level: 4,
                parent: 504635,
                children: [
                  {
                    key: 1319,
                    title: '存水弯/滤网',
                    isLeaf: 0,
                    level: 5,
                    parent: 504637,
                    children: [],
                  },
                  {
                    key: 1514,
                    title: '排水框架',
                    isLeaf: 0,
                    level: 5,
                    parent: 504637,
                    children: [],
                  },
                  { key: 2257, title: '排水管', isLeaf: 0, level: 5, parent: 504637, children: [] },
                  {
                    key: 2851,
                    title: '排水管盖子/过滤器',
                    isLeaf: 0,
                    level: 5,
                    parent: 504637,
                    children: [],
                  },
                  { key: 2170, title: '污水管', isLeaf: 0, level: 5, parent: 504637, children: [] },
                  {
                    key: 1932,
                    title: '管道疏通用品',
                    isLeaf: 0,
                    level: 5,
                    parent: 504637,
                    children: [],
                  },
                  {
                    key: 1407,
                    title: '管道疏通软杆',
                    isLeaf: 0,
                    level: 5,
                    parent: 504637,
                    children: [],
                  },
                ],
              },
              {
                key: 1963,
                title: '水槽配件',
                isLeaf: 1,
                level: 4,
                parent: 504635,
                children: [
                  { key: 2410, title: '水槽支架', isLeaf: 0, level: 5, parent: 1963, children: [] },
                ],
              },
              {
                key: 2996,
                title: '浴缸配件',
                isLeaf: 1,
                level: 4,
                parent: 504635,
                children: [
                  {
                    key: 505368,
                    title: '浴缸底座/支脚',
                    isLeaf: 0,
                    level: 5,
                    parent: 2996,
                    children: [],
                  },
                  { key: 5508, title: '浴缸裙边', isLeaf: 0, level: 5, parent: 2996, children: [] },
                  { key: 2463, title: '浴缸龙头', isLeaf: 0, level: 5, parent: 2996, children: [] },
                ],
              },
              {
                key: 2206,
                title: '淋浴部件',
                isLeaf: 1,
                level: 4,
                parent: 504635,
                children: [
                  {
                    key: 8320,
                    title: '浴缸/淋浴喷水系统',
                    isLeaf: 0,
                    level: 5,
                    parent: 2206,
                    children: [],
                  },
                  {
                    key: 4728,
                    title: '淋浴房底座',
                    isLeaf: 0,
                    level: 5,
                    parent: 2206,
                    children: [],
                  },
                  { key: 2088, title: '淋浴柱', isLeaf: 0, level: 5, parent: 2206, children: [] },
                  {
                    key: 5048,
                    title: '淋浴滤水器',
                    isLeaf: 0,
                    level: 5,
                    parent: 2206,
                    children: [],
                  },
                  {
                    key: 1779,
                    title: '淋浴门/淋浴间',
                    isLeaf: 0,
                    level: 5,
                    parent: 2206,
                    children: [],
                  },
                  {
                    key: 7130,
                    title: '淋浴隔断/围帘',
                    isLeaf: 0,
                    level: 5,
                    parent: 2206,
                    children: [],
                  },
                  {
                    key: 8277,
                    title: '电热淋浴器',
                    isLeaf: 0,
                    level: 5,
                    parent: 2206,
                    children: [],
                  },
                  { key: 581, title: '花洒', isLeaf: 0, level: 5, parent: 2206, children: [] },
                  {
                    key: 504638,
                    title: '花洒臂与连接器',
                    isLeaf: 0,
                    level: 5,
                    parent: 2206,
                    children: [],
                  },
                ],
              },
              {
                key: 2691,
                title: '马桶与坐浴盆配件',
                isLeaf: 1,
                level: 4,
                parent: 504635,
                children: [
                  {
                    key: 504634,
                    title: '坐浴盆水龙头和喷头',
                    isLeaf: 0,
                    level: 5,
                    parent: 2691,
                    children: [],
                  },
                  {
                    key: 1425,
                    title: '浮球活栓与挡板',
                    isLeaf: 0,
                    level: 5,
                    parent: 2691,
                    children: [],
                  },
                  {
                    key: 7358,
                    title: '马桶座垫罩',
                    isLeaf: 0,
                    level: 5,
                    parent: 2691,
                    children: [],
                  },
                  {
                    key: 7446,
                    title: '马桶座盖护罩',
                    isLeaf: 0,
                    level: 5,
                    parent: 2691,
                    children: [],
                  },
                  { key: 5665, title: '马桶水箱', isLeaf: 0, level: 5, parent: 2691, children: [] },
                  {
                    key: 2817,
                    title: '马桶水箱开关/扳手',
                    isLeaf: 0,
                    level: 5,
                    parent: 2691,
                    children: [],
                  },
                  {
                    key: 5666,
                    title: '马桶水箱盖',
                    isLeaf: 0,
                    level: 5,
                    parent: 2691,
                    children: [],
                  },
                  { key: 1865, title: '马桶盖', isLeaf: 0, level: 5, parent: 2691, children: [] },
                  { key: 2478, title: '马桶配件', isLeaf: 0, level: 5, parent: 2691, children: [] },
                ],
              },
              {
                key: 1489,
                title: '龙头配件',
                isLeaf: 1,
                level: 4,
                parent: 504635,
                children: [
                  {
                    key: 8116,
                    title: '水龙头手柄和控件',
                    isLeaf: 0,
                    level: 5,
                    parent: 1489,
                    children: [],
                  },
                  {
                    key: 8115,
                    title: '水龙头曝气器',
                    isLeaf: 0,
                    level: 5,
                    parent: 1489,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            key: 1810,
            title: '水管配件/支架',
            isLeaf: 0,
            level: 3,
            parent: 133,
            children: [
              {
                key: 2068,
                title: '喷嘴',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 6732,
                title: '垫圈/O形圈',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 499697,
                title: '壁挂承重器/安装支架',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 2634,
                title: '管夹',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 2909,
                title: '管帽/管塞',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 2359,
                title: '管接头',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 2611,
                title: '管道减压阀',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 1694,
                title: '管道法兰',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 2466,
                title: '管道阀',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
              {
                key: 2710,
                title: '转换接头',
                isLeaf: 0,
                level: 4,
                parent: 1810,
                children: [],
              },
            ],
          },
          {
            key: 6832,
            title: '浇水/喷水定时器',
            isLeaf: 0,
            level: 3,
            parent: 133,
            children: [],
          },
          {
            key: 2203,
            title: '管道修理工具包',
            isLeaf: 0,
            level: 3,
            parent: 133,
            children: [],
          },
          {
            key: 1673,
            title: '管道设备',
            isLeaf: 1,
            level: 3,
            parent: 133,
            children: [
              {
                key: 2032,
                title: '水龙头',
                isLeaf: 0,
                level: 4,
                parent: 1673,
                children: [],
              },
              {
                key: 499999,
                title: '浴室套件',
                isLeaf: 0,
                level: 4,
                parent: 1673,
                children: [],
              },
              {
                key: 1636,
                title: '浴缸',
                isLeaf: 0,
                level: 4,
                parent: 1673,
                children: [],
              },
              {
                key: 7244,
                title: '淋浴/隔间组装套装',
                isLeaf: 0,
                level: 4,
                parent: 1673,
                children: [],
              },
              {
                key: 2062,
                title: '马桶与坐浴盆',
                isLeaf: 1,
                level: 4,
                parent: 1673,
                children: [
                  { key: 2376, title: '坐浴盆', isLeaf: 0, level: 5, parent: 2062, children: [] },
                  { key: 1746, title: '尿壶', isLeaf: 0, level: 5, parent: 2062, children: [] },
                  {
                    key: 1921,
                    title: '马桶/坐便器',
                    isLeaf: 0,
                    level: 5,
                    parent: 2062,
                    children: [],
                  },
                ],
              },
              {
                key: 1687,
                title: '水槽',
                isLeaf: 1,
                level: 4,
                parent: 1673,
                children: [
                  {
                    key: 2757,
                    title: '厨房水槽/水池',
                    isLeaf: 0,
                    level: 5,
                    parent: 1687,
                    children: [],
                  },
                  { key: 2886, title: '浴室水槽', isLeaf: 0, level: 5, parent: 1687, children: [] },
                ],
              },
            ],
          },
          {
            key: 2273,
            title: '饮水机与净水器',
            isLeaf: 0,
            level: 3,
            parent: 133,
            children: [
              {
                key: 2171,
                title: '净水器配件',
                isLeaf: 0,
                level: 4,
                parent: 2273,
                children: [],
              },
              {
                key: 2406,
                title: '净水器外壳',
                isLeaf: 0,
                level: 4,
                parent: 2273,
                children: [],
              },
              {
                key: 2063,
                title: '净水器滤芯',
                isLeaf: 0,
                level: 4,
                parent: 2273,
                children: [],
              },
              {
                key: 2055,
                title: '前置管道净水器',
                isLeaf: 0,
                level: 4,
                parent: 2273,
                children: [],
              },
              {
                key: 1390,
                title: '蒸馏水器',
                isLeaf: 0,
                level: 4,
                parent: 2273,
                children: [],
              },
              {
                key: 1952,
                title: '软水器',
                isLeaf: 0,
                level: 4,
                parent: 2273,
                children: [],
              },
              {
                key: 5646,
                title: '软水盐',
                isLeaf: 0,
                level: 4,
                parent: 2273,
                children: [],
              },
              {
                key: 2343,
                title: '饮水机',
                isLeaf: 1,
                level: 4,
                parent: 2273,
                children: [
                  { key: 1354, title: '冰水机', isLeaf: 0, level: 5, parent: 2343, children: [] },
                  { key: 1821, title: '饮水器', isLeaf: 0, level: 5, parent: 2343, children: [] },
                ],
              },
            ],
          },
        ],
      },
      {
        key: 1974,
        title: '锁与钥匙',
        children: [
          {
            key: 6488,
            title: '钥匙坯',
            isLeaf: 0,
            level: 3,
            parent: 1974,
            children: [],
          },
          {
            key: 8067,
            title: '钥匙帽',
            isLeaf: 0,
            level: 3,
            parent: 1974,
            children: [],
          },
          {
            key: 503730,
            title: '锁和插销',
            isLeaf: 0,
            level: 3,
            parent: 1974,
            children: [],
          },
          {
            key: 1870,
            title: '门卡门禁系统',
            isLeaf: 0,
            level: 3,
            parent: 1974,
            children: [],
          },
        ],
      },
    ],
  },
];

export default tableData;
